### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by styfle**
The npm name is different in this fork so I went ahead and updated the readme

### CODE REVIEW

**Comment by styfle** [comment]
What's the governance model for this repo?

Do we still want to stick with 2 reviews required?

**Comment by UziTech** [comment]
I was thinking we should. Just to be consistent.

**Comment by joshbruce** [comment]
I agree. Maybe we should even use the same templates we use in the main Marked repo? (Drawback being that changes to the templates would need to be made in multiple places.

**Comment by UziTech** [comment]
I don't know if we need templates for this repo. I don't think we will have nearly as many outside issues/PRs

**Pull request merged**
